version: '3.8'
services:
  db:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"
    volumes:
      - db-volume:/var/lib/mysql:rw
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - default
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=studentsclub
      - DB_PORT=3306
    
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - default

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
      - /app/.next
    networks:
      - default
volumes:
  db-volume: